name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Prepare data
        run: |
          source .venv/bin/activate
          python data/prepare.py

      - name: Train model
        run: |
          source .venv/bin/activate
          python models/train_lgb.py

      - name: Backtest
        run: |
          source .venv/bin/activate
          python backtest/run_vectorbt.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backtest-results
          path: |
            backtest/stats.csv
            backtest/equity_curve.png
